events {}

http {
    include "C:/Users/fatim/Downloads/nginx-1.31.2/nginx-1.31.2/conf/mime.types";

    server {
        listen 80;

        location ^~ /api/prompts {
            rewrite ^/api/prompts(.*) /prompts$1 break;
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location ^~ /api/reviews {
            rewrite ^/api/reviews(.*) /reviews$1 break;
            proxy_pass http://127.0.0.1:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            root "C:/Users/fatim/Documents/Adept Tech Solutions Summer Internship 2026/Task 5/prompt-manager-services-system/frontend/dist";
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}